scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093 

